services: 
    catapp:
      container_name: catapp
      build:
        context: .
        dockerfile: catApplication/Dockerfile
      ports:
        - "8080:8080"
      environment:
        - MSSQL_SA_PASSWORD=Password123
      depends_on:
        - catdb
      
      
    catdb:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      container_name: catdb
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password123
      ports:
      - "1433:1433"