services: 
    catapp:
      container_name: catapp
      build: .
      ports:
        - "8080:8080"
      environment:
        - MSSQL_SA_PASSWORD=Password123
      depends_on:
        - catdb
#      command: ["dotnet", "ef", "database", "update"]
      
      
    catdb:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      container_name: catdb
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password123
      ports:
      - "1433:1433"
      healthcheck:
        test: [ "CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password123", "-Q", "SELECT 1" ]
        interval: 10s
        timeout: 10s
        retries: 5