# This is a generated file. Not intended for manual editing.
services:
  catapp:
    build:
      context: "C:\\projects\\catApplication\\catApplication"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "catapplication:dev"
    ports:
    - "127.0.0.1:57014:57100"
    - "127.0.0.1:65135:57300"
    volumes:
    - "C:\\Users\\sboto\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\projects\\catApplication\\catApplication:/app:rw"
    - "C:\\projects\\catApplication:/src:rw"
    - "C:\\Users\\sboto\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.5\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\sboto\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\sboto\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_13_23_19_24:/var/opt/rider-debugger:rw"
    working_dir: "/app"
